package com.nationsky.seccom.uc.model;

import java.util.Date;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_id
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_name
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_alias
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_email
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_phone
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_address
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.company_url
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String companyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.ldap_config_index
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String ldapConfigIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.status
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.update_time
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company.create_time
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_id
     *
     * @return the value of sc_uc_company.company_id
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_id
     *
     * @param companyId the value for sc_uc_company.company_id
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_name
     *
     * @return the value of sc_uc_company.company_name
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_name
     *
     * @param companyName the value for sc_uc_company.company_name
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_alias
     *
     * @return the value of sc_uc_company.company_alias
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyAlias() {
        return companyAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_alias
     *
     * @param companyAlias the value for sc_uc_company.company_alias
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyAlias(String companyAlias) {
        this.companyAlias = companyAlias == null ? null : companyAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_email
     *
     * @return the value of sc_uc_company.company_email
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_email
     *
     * @param companyEmail the value for sc_uc_company.company_email
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail == null ? null : companyEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_phone
     *
     * @return the value of sc_uc_company.company_phone
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_phone
     *
     * @param companyPhone the value for sc_uc_company.company_phone
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone == null ? null : companyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_address
     *
     * @return the value of sc_uc_company.company_address
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_address
     *
     * @param companyAddress the value for sc_uc_company.company_address
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.company_url
     *
     * @return the value of sc_uc_company.company_url
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getCompanyUrl() {
        return companyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.company_url
     *
     * @param companyUrl the value for sc_uc_company.company_url
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCompanyUrl(String companyUrl) {
        this.companyUrl = companyUrl == null ? null : companyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.ldap_config_index
     *
     * @return the value of sc_uc_company.ldap_config_index
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getLdapConfigIndex() {
        return ldapConfigIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.ldap_config_index
     *
     * @param ldapConfigIndex the value for sc_uc_company.ldap_config_index
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setLdapConfigIndex(String ldapConfigIndex) {
        this.ldapConfigIndex = ldapConfigIndex == null ? null : ldapConfigIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.status
     *
     * @return the value of sc_uc_company.status
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.status
     *
     * @param status the value for sc_uc_company.status
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.update_time
     *
     * @return the value of sc_uc_company.update_time
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.update_time
     *
     * @param updateTime the value for sc_uc_company.update_time
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company.create_time
     *
     * @return the value of sc_uc_company.create_time
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company.create_time
     *
     * @param createTime the value for sc_uc_company.create_time
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}