package com.nationsky.seccom.uc.model;

public class CompanyRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company_relation.ancestor_company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String ancestorCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company_relation.descendant_company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String descendantCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_company_relation.path_length
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private Integer pathLength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company_relation.ancestor_company_id
     *
     * @return the value of sc_uc_company_relation.ancestor_company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getAncestorCompanyId() {
        return ancestorCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company_relation.ancestor_company_id
     *
     * @param ancestorCompanyId the value for sc_uc_company_relation.ancestor_company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setAncestorCompanyId(String ancestorCompanyId) {
        this.ancestorCompanyId = ancestorCompanyId == null ? null : ancestorCompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company_relation.descendant_company_id
     *
     * @return the value of sc_uc_company_relation.descendant_company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getDescendantCompanyId() {
        return descendantCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company_relation.descendant_company_id
     *
     * @param descendantCompanyId the value for sc_uc_company_relation.descendant_company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setDescendantCompanyId(String descendantCompanyId) {
        this.descendantCompanyId = descendantCompanyId == null ? null : descendantCompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_company_relation.path_length
     *
     * @return the value of sc_uc_company_relation.path_length
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public Integer getPathLength() {
        return pathLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_company_relation.path_length
     *
     * @param pathLength the value for sc_uc_company_relation.path_length
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setPathLength(Integer pathLength) {
        this.pathLength = pathLength;
    }
}