package com.nationsky.seccom.uc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeptExtensionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public DeptExtensionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(String value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(String value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(String value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(String value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(String value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLike(String value) {
            addCriterion("dept_id like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotLike(String value) {
            addCriterion("dept_id not like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<String> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<String> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(String value1, String value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(String value1, String value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdIsNull() {
            addCriterion("extension_id is null");
            return (Criteria) this;
        }

        public Criteria andExtensionIdIsNotNull() {
            addCriterion("extension_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionIdEqualTo(String value) {
            addCriterion("extension_id =", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdNotEqualTo(String value) {
            addCriterion("extension_id <>", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdGreaterThan(String value) {
            addCriterion("extension_id >", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdGreaterThanOrEqualTo(String value) {
            addCriterion("extension_id >=", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdLessThan(String value) {
            addCriterion("extension_id <", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdLessThanOrEqualTo(String value) {
            addCriterion("extension_id <=", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdLike(String value) {
            addCriterion("extension_id like", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdNotLike(String value) {
            addCriterion("extension_id not like", value, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdIn(List<String> values) {
            addCriterion("extension_id in", values, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdNotIn(List<String> values) {
            addCriterion("extension_id not in", values, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdBetween(String value1, String value2) {
            addCriterion("extension_id between", value1, value2, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionIdNotBetween(String value1, String value2) {
            addCriterion("extension_id not between", value1, value2, "extensionId");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIsNull() {
            addCriterion("extension_value is null");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIsNotNull() {
            addCriterion("extension_value is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionValueEqualTo(String value) {
            addCriterion("extension_value =", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueNotEqualTo(String value) {
            addCriterion("extension_value <>", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueGreaterThan(String value) {
            addCriterion("extension_value >", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueGreaterThanOrEqualTo(String value) {
            addCriterion("extension_value >=", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueLessThan(String value) {
            addCriterion("extension_value <", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueLessThanOrEqualTo(String value) {
            addCriterion("extension_value <=", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueLike(String value) {
            addCriterion("extension_value like", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueNotLike(String value) {
            addCriterion("extension_value not like", value, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIn(List<String> values) {
            addCriterion("extension_value in", values, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueNotIn(List<String> values) {
            addCriterion("extension_value not in", values, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueBetween(String value1, String value2) {
            addCriterion("extension_value between", value1, value2, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andExtensionValueNotBetween(String value1, String value2) {
            addCriterion("extension_value not between", value1, value2, "extensionValue");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 23 15:30:57 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}