package com.nationsky.seccom.uc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeptBasicInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public DeptBasicInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(String value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(String value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(String value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(String value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(String value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLike(String value) {
            addCriterion("dept_id like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotLike(String value) {
            addCriterion("dept_id not like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<String> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<String> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(String value1, String value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(String value1, String value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNull() {
            addCriterion("dept_name is null");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNotNull() {
            addCriterion("dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andDeptNameEqualTo(String value) {
            addCriterion("dept_name =", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotEqualTo(String value) {
            addCriterion("dept_name <>", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThan(String value) {
            addCriterion("dept_name >", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("dept_name >=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThan(String value) {
            addCriterion("dept_name <", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThanOrEqualTo(String value) {
            addCriterion("dept_name <=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLike(String value) {
            addCriterion("dept_name like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotLike(String value) {
            addCriterion("dept_name not like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameIn(List<String> values) {
            addCriterion("dept_name in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotIn(List<String> values) {
            addCriterion("dept_name not in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameBetween(String value1, String value2) {
            addCriterion("dept_name between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotBetween(String value1, String value2) {
            addCriterion("dept_name not between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneIsNull() {
            addCriterion("dept_phone is null");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneIsNotNull() {
            addCriterion("dept_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneEqualTo(String value) {
            addCriterion("dept_phone =", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotEqualTo(String value) {
            addCriterion("dept_phone <>", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneGreaterThan(String value) {
            addCriterion("dept_phone >", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("dept_phone >=", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneLessThan(String value) {
            addCriterion("dept_phone <", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneLessThanOrEqualTo(String value) {
            addCriterion("dept_phone <=", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneLike(String value) {
            addCriterion("dept_phone like", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotLike(String value) {
            addCriterion("dept_phone not like", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneIn(List<String> values) {
            addCriterion("dept_phone in", values, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotIn(List<String> values) {
            addCriterion("dept_phone not in", values, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneBetween(String value1, String value2) {
            addCriterion("dept_phone between", value1, value2, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotBetween(String value1, String value2) {
            addCriterion("dept_phone not between", value1, value2, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptInfoIsNull() {
            addCriterion("dept_info is null");
            return (Criteria) this;
        }

        public Criteria andDeptInfoIsNotNull() {
            addCriterion("dept_info is not null");
            return (Criteria) this;
        }

        public Criteria andDeptInfoEqualTo(String value) {
            addCriterion("dept_info =", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoNotEqualTo(String value) {
            addCriterion("dept_info <>", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoGreaterThan(String value) {
            addCriterion("dept_info >", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoGreaterThanOrEqualTo(String value) {
            addCriterion("dept_info >=", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoLessThan(String value) {
            addCriterion("dept_info <", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoLessThanOrEqualTo(String value) {
            addCriterion("dept_info <=", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoLike(String value) {
            addCriterion("dept_info like", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoNotLike(String value) {
            addCriterion("dept_info not like", value, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoIn(List<String> values) {
            addCriterion("dept_info in", values, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoNotIn(List<String> values) {
            addCriterion("dept_info not in", values, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoBetween(String value1, String value2) {
            addCriterion("dept_info between", value1, value2, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptInfoNotBetween(String value1, String value2) {
            addCriterion("dept_info not between", value1, value2, "deptInfo");
            return (Criteria) this;
        }

        public Criteria andDeptOrderIsNull() {
            addCriterion("dept_order is null");
            return (Criteria) this;
        }

        public Criteria andDeptOrderIsNotNull() {
            addCriterion("dept_order is not null");
            return (Criteria) this;
        }

        public Criteria andDeptOrderEqualTo(Integer value) {
            addCriterion("dept_order =", value, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderNotEqualTo(Integer value) {
            addCriterion("dept_order <>", value, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderGreaterThan(Integer value) {
            addCriterion("dept_order >", value, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_order >=", value, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderLessThan(Integer value) {
            addCriterion("dept_order <", value, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderLessThanOrEqualTo(Integer value) {
            addCriterion("dept_order <=", value, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderIn(List<Integer> values) {
            addCriterion("dept_order in", values, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderNotIn(List<Integer> values) {
            addCriterion("dept_order not in", values, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderBetween(Integer value1, Integer value2) {
            addCriterion("dept_order between", value1, value2, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_order not between", value1, value2, "deptOrder");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdIsNull() {
            addCriterion("dept_leader_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdIsNotNull() {
            addCriterion("dept_leader_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdEqualTo(String value) {
            addCriterion("dept_leader_id =", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdNotEqualTo(String value) {
            addCriterion("dept_leader_id <>", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdGreaterThan(String value) {
            addCriterion("dept_leader_id >", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdGreaterThanOrEqualTo(String value) {
            addCriterion("dept_leader_id >=", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdLessThan(String value) {
            addCriterion("dept_leader_id <", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdLessThanOrEqualTo(String value) {
            addCriterion("dept_leader_id <=", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdLike(String value) {
            addCriterion("dept_leader_id like", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdNotLike(String value) {
            addCriterion("dept_leader_id not like", value, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdIn(List<String> values) {
            addCriterion("dept_leader_id in", values, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdNotIn(List<String> values) {
            addCriterion("dept_leader_id not in", values, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdBetween(String value1, String value2) {
            addCriterion("dept_leader_id between", value1, value2, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andDeptLeaderIdNotBetween(String value1, String value2) {
            addCriterion("dept_leader_id not between", value1, value2, "deptLeaderId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeptSourceIsNull() {
            addCriterion("dept_source is null");
            return (Criteria) this;
        }

        public Criteria andDeptSourceIsNotNull() {
            addCriterion("dept_source is not null");
            return (Criteria) this;
        }

        public Criteria andDeptSourceEqualTo(String value) {
            addCriterion("dept_source =", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceNotEqualTo(String value) {
            addCriterion("dept_source <>", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceGreaterThan(String value) {
            addCriterion("dept_source >", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceGreaterThanOrEqualTo(String value) {
            addCriterion("dept_source >=", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceLessThan(String value) {
            addCriterion("dept_source <", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceLessThanOrEqualTo(String value) {
            addCriterion("dept_source <=", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceLike(String value) {
            addCriterion("dept_source like", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceNotLike(String value) {
            addCriterion("dept_source not like", value, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceIn(List<String> values) {
            addCriterion("dept_source in", values, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceNotIn(List<String> values) {
            addCriterion("dept_source not in", values, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceBetween(String value1, String value2) {
            addCriterion("dept_source between", value1, value2, "deptSource");
            return (Criteria) this;
        }

        public Criteria andDeptSourceNotBetween(String value1, String value2) {
            addCriterion("dept_source not between", value1, value2, "deptSource");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdIsNull() {
            addCriterion("previous_dept_id is null");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdIsNotNull() {
            addCriterion("previous_dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdEqualTo(String value) {
            addCriterion("previous_dept_id =", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdNotEqualTo(String value) {
            addCriterion("previous_dept_id <>", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdGreaterThan(String value) {
            addCriterion("previous_dept_id >", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("previous_dept_id >=", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdLessThan(String value) {
            addCriterion("previous_dept_id <", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdLessThanOrEqualTo(String value) {
            addCriterion("previous_dept_id <=", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdLike(String value) {
            addCriterion("previous_dept_id like", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdNotLike(String value) {
            addCriterion("previous_dept_id not like", value, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdIn(List<String> values) {
            addCriterion("previous_dept_id in", values, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdNotIn(List<String> values) {
            addCriterion("previous_dept_id not in", values, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdBetween(String value1, String value2) {
            addCriterion("previous_dept_id between", value1, value2, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andPreviousDeptIdNotBetween(String value1, String value2) {
            addCriterion("previous_dept_id not between", value1, value2, "previousDeptId");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptIsNull() {
            addCriterion("is_root_dept is null");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptIsNotNull() {
            addCriterion("is_root_dept is not null");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptEqualTo(String value) {
            addCriterion("is_root_dept =", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptNotEqualTo(String value) {
            addCriterion("is_root_dept <>", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptGreaterThan(String value) {
            addCriterion("is_root_dept >", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptGreaterThanOrEqualTo(String value) {
            addCriterion("is_root_dept >=", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptLessThan(String value) {
            addCriterion("is_root_dept <", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptLessThanOrEqualTo(String value) {
            addCriterion("is_root_dept <=", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptLike(String value) {
            addCriterion("is_root_dept like", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptNotLike(String value) {
            addCriterion("is_root_dept not like", value, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptIn(List<String> values) {
            addCriterion("is_root_dept in", values, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptNotIn(List<String> values) {
            addCriterion("is_root_dept not in", values, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptBetween(String value1, String value2) {
            addCriterion("is_root_dept between", value1, value2, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andIsRootDeptNotBetween(String value1, String value2) {
            addCriterion("is_root_dept not between", value1, value2, "isRootDept");
            return (Criteria) this;
        }

        public Criteria andFullPathIsNull() {
            addCriterion("full_path is null");
            return (Criteria) this;
        }

        public Criteria andFullPathIsNotNull() {
            addCriterion("full_path is not null");
            return (Criteria) this;
        }

        public Criteria andFullPathEqualTo(String value) {
            addCriterion("full_path =", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathNotEqualTo(String value) {
            addCriterion("full_path <>", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathGreaterThan(String value) {
            addCriterion("full_path >", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathGreaterThanOrEqualTo(String value) {
            addCriterion("full_path >=", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathLessThan(String value) {
            addCriterion("full_path <", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathLessThanOrEqualTo(String value) {
            addCriterion("full_path <=", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathLike(String value) {
            addCriterion("full_path like", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathNotLike(String value) {
            addCriterion("full_path not like", value, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathIn(List<String> values) {
            addCriterion("full_path in", values, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathNotIn(List<String> values) {
            addCriterion("full_path not in", values, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathBetween(String value1, String value2) {
            addCriterion("full_path between", value1, value2, "fullPath");
            return (Criteria) this;
        }

        public Criteria andFullPathNotBetween(String value1, String value2) {
            addCriterion("full_path not between", value1, value2, "fullPath");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 09 17:48:11 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}