package com.nationsky.seccom.uc.model;

import java.util.Date;

public class DeptBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.company_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_name
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_phone
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String deptPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_info
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String deptInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_order
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private Integer deptOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_leader_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String deptLeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.status
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.dept_source
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String deptSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.previous_dept_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String previousDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.is_root_dept
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String isRootDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.full_path
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private String fullPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.update_time
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_dept_basic.create_time
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_id
     *
     * @return the value of sc_uc_dept_basic.dept_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_id
     *
     * @param deptId the value for sc_uc_dept_basic.dept_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.company_id
     *
     * @return the value of sc_uc_dept_basic.company_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.company_id
     *
     * @param companyId the value for sc_uc_dept_basic.company_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_name
     *
     * @return the value of sc_uc_dept_basic.dept_name
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_name
     *
     * @param deptName the value for sc_uc_dept_basic.dept_name
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_phone
     *
     * @return the value of sc_uc_dept_basic.dept_phone
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getDeptPhone() {
        return deptPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_phone
     *
     * @param deptPhone the value for sc_uc_dept_basic.dept_phone
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptPhone(String deptPhone) {
        this.deptPhone = deptPhone == null ? null : deptPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_info
     *
     * @return the value of sc_uc_dept_basic.dept_info
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getDeptInfo() {
        return deptInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_info
     *
     * @param deptInfo the value for sc_uc_dept_basic.dept_info
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptInfo(String deptInfo) {
        this.deptInfo = deptInfo == null ? null : deptInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_order
     *
     * @return the value of sc_uc_dept_basic.dept_order
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public Integer getDeptOrder() {
        return deptOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_order
     *
     * @param deptOrder the value for sc_uc_dept_basic.dept_order
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptOrder(Integer deptOrder) {
        this.deptOrder = deptOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_leader_id
     *
     * @return the value of sc_uc_dept_basic.dept_leader_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getDeptLeaderId() {
        return deptLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_leader_id
     *
     * @param deptLeaderId the value for sc_uc_dept_basic.dept_leader_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptLeaderId(String deptLeaderId) {
        this.deptLeaderId = deptLeaderId == null ? null : deptLeaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.status
     *
     * @return the value of sc_uc_dept_basic.status
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.status
     *
     * @param status the value for sc_uc_dept_basic.status
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.dept_source
     *
     * @return the value of sc_uc_dept_basic.dept_source
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getDeptSource() {
        return deptSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.dept_source
     *
     * @param deptSource the value for sc_uc_dept_basic.dept_source
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setDeptSource(String deptSource) {
        this.deptSource = deptSource == null ? null : deptSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.previous_dept_id
     *
     * @return the value of sc_uc_dept_basic.previous_dept_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getPreviousDeptId() {
        return previousDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.previous_dept_id
     *
     * @param previousDeptId the value for sc_uc_dept_basic.previous_dept_id
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setPreviousDeptId(String previousDeptId) {
        this.previousDeptId = previousDeptId == null ? null : previousDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.is_root_dept
     *
     * @return the value of sc_uc_dept_basic.is_root_dept
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getIsRootDept() {
        return isRootDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.is_root_dept
     *
     * @param isRootDept the value for sc_uc_dept_basic.is_root_dept
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setIsRootDept(String isRootDept) {
        this.isRootDept = isRootDept == null ? null : isRootDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.full_path
     *
     * @return the value of sc_uc_dept_basic.full_path
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.full_path
     *
     * @param fullPath the value for sc_uc_dept_basic.full_path
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath == null ? null : fullPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.update_time
     *
     * @return the value of sc_uc_dept_basic.update_time
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.update_time
     *
     * @param updateTime the value for sc_uc_dept_basic.update_time
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_dept_basic.create_time
     *
     * @return the value of sc_uc_dept_basic.create_time
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_dept_basic.create_time
     *
     * @param createTime the value for sc_uc_dept_basic.create_time
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}