package com.nationsky.seccom.uc.model;

import java.util.Date;

public class Extension {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_extension.id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_extension.extension_name_en
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String extensionNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_extension.extension_name_ch
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String extensionNameCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_extension.extension_type
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String extensionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_extension.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_extension.id
     *
     * @return the value of sc_uc_extension.id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_extension.id
     *
     * @param id the value for sc_uc_extension.id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_extension.extension_name_en
     *
     * @return the value of sc_uc_extension.extension_name_en
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getExtensionNameEn() {
        return extensionNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_extension.extension_name_en
     *
     * @param extensionNameEn the value for sc_uc_extension.extension_name_en
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setExtensionNameEn(String extensionNameEn) {
        this.extensionNameEn = extensionNameEn == null ? null : extensionNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_extension.extension_name_ch
     *
     * @return the value of sc_uc_extension.extension_name_ch
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getExtensionNameCh() {
        return extensionNameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_extension.extension_name_ch
     *
     * @param extensionNameCh the value for sc_uc_extension.extension_name_ch
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setExtensionNameCh(String extensionNameCh) {
        this.extensionNameCh = extensionNameCh == null ? null : extensionNameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_extension.extension_type
     *
     * @return the value of sc_uc_extension.extension_type
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getExtensionType() {
        return extensionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_extension.extension_type
     *
     * @param extensionType the value for sc_uc_extension.extension_type
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setExtensionType(String extensionType) {
        this.extensionType = extensionType == null ? null : extensionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_extension.create_time
     *
     * @return the value of sc_uc_extension.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_extension.create_time
     *
     * @param createTime the value for sc_uc_extension.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}