package com.nationsky.seccom.uc.model;

import java.util.Date;

public class UserBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_id
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.real_name
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.nick_name
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_sex
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_id_card
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_email
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_telephone
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_mobile
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_address
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_birth_day
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userBirthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.is_married
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String isMarried;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.user_source
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String userSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.status
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.update_time
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_basic.create_time
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_id
     *
     * @return the value of sc_uc_user_basic.user_id
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_id
     *
     * @param userId the value for sc_uc_user_basic.user_id
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.real_name
     *
     * @return the value of sc_uc_user_basic.real_name
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.real_name
     *
     * @param realName the value for sc_uc_user_basic.real_name
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.nick_name
     *
     * @return the value of sc_uc_user_basic.nick_name
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.nick_name
     *
     * @param nickName the value for sc_uc_user_basic.nick_name
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_sex
     *
     * @return the value of sc_uc_user_basic.user_sex
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_sex
     *
     * @param userSex the value for sc_uc_user_basic.user_sex
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_id_card
     *
     * @return the value of sc_uc_user_basic.user_id_card
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserIdCard() {
        return userIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_id_card
     *
     * @param userIdCard the value for sc_uc_user_basic.user_id_card
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserIdCard(String userIdCard) {
        this.userIdCard = userIdCard == null ? null : userIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_email
     *
     * @return the value of sc_uc_user_basic.user_email
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_email
     *
     * @param userEmail the value for sc_uc_user_basic.user_email
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_telephone
     *
     * @return the value of sc_uc_user_basic.user_telephone
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_telephone
     *
     * @param userTelephone the value for sc_uc_user_basic.user_telephone
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_mobile
     *
     * @return the value of sc_uc_user_basic.user_mobile
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_mobile
     *
     * @param userMobile the value for sc_uc_user_basic.user_mobile
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_address
     *
     * @return the value of sc_uc_user_basic.user_address
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_address
     *
     * @param userAddress the value for sc_uc_user_basic.user_address
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_birth_day
     *
     * @return the value of sc_uc_user_basic.user_birth_day
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserBirthDay() {
        return userBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_birth_day
     *
     * @param userBirthDay the value for sc_uc_user_basic.user_birth_day
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserBirthDay(String userBirthDay) {
        this.userBirthDay = userBirthDay == null ? null : userBirthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.is_married
     *
     * @return the value of sc_uc_user_basic.is_married
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getIsMarried() {
        return isMarried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.is_married
     *
     * @param isMarried the value for sc_uc_user_basic.is_married
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setIsMarried(String isMarried) {
        this.isMarried = isMarried == null ? null : isMarried.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.user_source
     *
     * @return the value of sc_uc_user_basic.user_source
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getUserSource() {
        return userSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.user_source
     *
     * @param userSource the value for sc_uc_user_basic.user_source
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUserSource(String userSource) {
        this.userSource = userSource == null ? null : userSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.status
     *
     * @return the value of sc_uc_user_basic.status
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.status
     *
     * @param status the value for sc_uc_user_basic.status
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.update_time
     *
     * @return the value of sc_uc_user_basic.update_time
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.update_time
     *
     * @param updateTime the value for sc_uc_user_basic.update_time
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_basic.create_time
     *
     * @return the value of sc_uc_user_basic.create_time
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_basic.create_time
     *
     * @param createTime the value for sc_uc_user_basic.create_time
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}