package com.nationsky.seccom.uc.model;

import java.util.Date;

public class UserExtension {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_extension.id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_extension.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_extension.extension_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String extensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_extension.extension_value
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String extensionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_extension.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_extension.id
     *
     * @return the value of sc_uc_user_extension.id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_extension.id
     *
     * @param id the value for sc_uc_user_extension.id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_extension.user_id
     *
     * @return the value of sc_uc_user_extension.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_extension.user_id
     *
     * @param userId the value for sc_uc_user_extension.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_extension.extension_id
     *
     * @return the value of sc_uc_user_extension.extension_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getExtensionId() {
        return extensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_extension.extension_id
     *
     * @param extensionId the value for sc_uc_user_extension.extension_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setExtensionId(String extensionId) {
        this.extensionId = extensionId == null ? null : extensionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_extension.extension_value
     *
     * @return the value of sc_uc_user_extension.extension_value
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getExtensionValue() {
        return extensionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_extension.extension_value
     *
     * @param extensionValue the value for sc_uc_user_extension.extension_value
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setExtensionValue(String extensionValue) {
        this.extensionValue = extensionValue == null ? null : extensionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_extension.create_time
     *
     * @return the value of sc_uc_user_extension.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_extension.create_time
     *
     * @param createTime the value for sc_uc_user_extension.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}