package com.nationsky.seccom.uc.model;

public class UserDeptRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_dept.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_dept.company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_dept.dept_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_dept.position_order
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private Integer positionOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_dept.job_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_user_dept.status
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_dept.user_id
     *
     * @return the value of sc_uc_user_dept.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_dept.user_id
     *
     * @param userId the value for sc_uc_user_dept.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_dept.company_id
     *
     * @return the value of sc_uc_user_dept.company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_dept.company_id
     *
     * @param companyId the value for sc_uc_user_dept.company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_dept.dept_id
     *
     * @return the value of sc_uc_user_dept.dept_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_dept.dept_id
     *
     * @param deptId the value for sc_uc_user_dept.dept_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_dept.position_order
     *
     * @return the value of sc_uc_user_dept.position_order
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public Integer getPositionOrder() {
        return positionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_dept.position_order
     *
     * @param positionOrder the value for sc_uc_user_dept.position_order
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setPositionOrder(Integer positionOrder) {
        this.positionOrder = positionOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_dept.job_id
     *
     * @return the value of sc_uc_user_dept.job_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_dept.job_id
     *
     * @param jobId the value for sc_uc_user_dept.job_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_user_dept.status
     *
     * @return the value of sc_uc_user_dept.status
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_user_dept.status
     *
     * @param status the value for sc_uc_user_dept.status
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}