package com.nationsky.seccom.uc.model;

import java.util.Date;

public class UserIdLoginAccountRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.login_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.login_name
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.password
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.user_head
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String userHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.person_sign
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String personSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.status
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_uc_login.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.login_id
     *
     * @return the value of sc_uc_login.login_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.login_id
     *
     * @param loginId the value for sc_uc_login.login_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.company_id
     *
     * @return the value of sc_uc_login.company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.company_id
     *
     * @param companyId the value for sc_uc_login.company_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.user_id
     *
     * @return the value of sc_uc_login.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.user_id
     *
     * @param userId the value for sc_uc_login.user_id
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.login_name
     *
     * @return the value of sc_uc_login.login_name
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.login_name
     *
     * @param loginName the value for sc_uc_login.login_name
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.password
     *
     * @return the value of sc_uc_login.password
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.password
     *
     * @param password the value for sc_uc_login.password
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.user_head
     *
     * @return the value of sc_uc_login.user_head
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getUserHead() {
        return userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.user_head
     *
     * @param userHead the value for sc_uc_login.user_head
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setUserHead(String userHead) {
        this.userHead = userHead == null ? null : userHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.person_sign
     *
     * @return the value of sc_uc_login.person_sign
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getPersonSign() {
        return personSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.person_sign
     *
     * @param personSign the value for sc_uc_login.person_sign
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setPersonSign(String personSign) {
        this.personSign = personSign == null ? null : personSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.status
     *
     * @return the value of sc_uc_login.status
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.status
     *
     * @param status the value for sc_uc_login.status
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_uc_login.create_time
     *
     * @return the value of sc_uc_login.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_uc_login.create_time
     *
     * @param createTime the value for sc_uc_login.create_time
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}