package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.CompanyRelation;
import com.nationsky.seccom.uc.model.CompanyRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int countByExample(CompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int deleteByExample(CompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int insert(CompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int insertSelective(CompanyRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    List<CompanyRelation> selectByExample(CompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") CompanyRelation record, @Param("example") CompanyRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_company_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByExample(@Param("record") CompanyRelation record, @Param("example") CompanyRelationExample example);
}