package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.DeptExtension;
import com.nationsky.seccom.uc.model.DeptExtensionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int countByExample(DeptExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int deleteByExample(DeptExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int insert(DeptExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int insertSelective(DeptExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    List<DeptExtension> selectByExample(DeptExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    DeptExtension selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") DeptExtension record, @Param("example") DeptExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int updateByExample(@Param("record") DeptExtension record, @Param("example") DeptExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int updateByPrimaryKeySelective(DeptExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_extension
     *
     * @mbggenerated Tue Jun 23 15:30:57 CST 2015
     */
    int updateByPrimaryKey(DeptExtension record);
}