package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.DeptRelation;
import com.nationsky.seccom.uc.model.DeptRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int countByExample(DeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int deleteByExample(DeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int insert(DeptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int insertSelective(DeptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    List<DeptRelation> selectByExample(DeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") DeptRelation record, @Param("example") DeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_relation
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByExample(@Param("record") DeptRelation record, @Param("example") DeptRelationExample example);
}