package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.DeptBasicInfo;
import com.nationsky.seccom.uc.model.DeptBasicInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int countByExample(DeptBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int deleteByExample(DeptBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int deleteByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int insert(DeptBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int insertSelective(DeptBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    List<DeptBasicInfo> selectByExample(DeptBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    DeptBasicInfo selectByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByExampleSelective(@Param("record") DeptBasicInfo record, @Param("example") DeptBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByExample(@Param("record") DeptBasicInfo record, @Param("example") DeptBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByPrimaryKeySelective(DeptBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_dept_basic
     *
     * @mbggenerated Tue Jun 09 17:48:11 CST 2015
     */
    int updateByPrimaryKey(DeptBasicInfo record);
}