package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.Extension;
import com.nationsky.seccom.uc.model.ExtensionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int countByExample(ExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int deleteByExample(ExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int insert(Extension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int insertSelective(Extension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    List<Extension> selectByExample(ExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    Extension selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") Extension record, @Param("example") ExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByExample(@Param("record") Extension record, @Param("example") ExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByPrimaryKeySelective(Extension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByPrimaryKey(Extension record);
}