package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.JobDict;
import com.nationsky.seccom.uc.model.JobDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int countByExample(JobDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int deleteByExample(JobDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int deleteByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int insert(JobDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int insertSelective(JobDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    List<JobDict> selectByExample(JobDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    JobDict selectByPrimaryKey(String jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") JobDict record, @Param("example") JobDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int updateByExample(@Param("record") JobDict record, @Param("example") JobDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int updateByPrimaryKeySelective(JobDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_job
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int updateByPrimaryKey(JobDict record);
}