package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.UserExtension;
import com.nationsky.seccom.uc.model.UserExtensionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int countByExample(UserExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int deleteByExample(UserExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int insert(UserExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int insertSelective(UserExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    List<UserExtension> selectByExample(UserExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    UserExtension selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserExtension record, @Param("example") UserExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByExample(@Param("record") UserExtension record, @Param("example") UserExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByPrimaryKeySelective(UserExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_extension
     *
     * @mbggenerated Thu Jun 18 13:44:36 CST 2015
     */
    int updateByPrimaryKey(UserExtension record);
}