package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.UserDeptRelation;
import com.nationsky.seccom.uc.model.UserDeptRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDeptRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int countByExample(UserDeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int deleteByExample(UserDeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int insert(UserDeptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int insertSelective(UserDeptRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    List<UserDeptRelation> selectByExample(UserDeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserDeptRelation record, @Param("example") UserDeptRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_dept
     *
     * @mbggenerated Tue Jun 16 16:41:26 CST 2015
     */
    int updateByExample(@Param("record") UserDeptRelation record, @Param("example") UserDeptRelationExample example);
}