package com.nationsky.seccom.uc.dao;

import com.nationsky.seccom.uc.model.UserBasicInfo;
import com.nationsky.seccom.uc.model.UserBasicInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int countByExample(UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int deleteByExample(UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int insert(UserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int insertSelective(UserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    List<UserBasicInfo> selectByExample(UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    UserBasicInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserBasicInfo record, @Param("example") UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int updateByExample(@Param("record") UserBasicInfo record, @Param("example") UserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int updateByPrimaryKeySelective(UserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_uc_user_basic
     *
     * @mbggenerated Tue Jun 09 17:48:10 CST 2015
     */
    int updateByPrimaryKey(UserBasicInfo record);
}